---
- name: Demonstration of ansible-bender functionality
  hosts: all
  connection: buildah
  vars:
    ansible_bender:
      base_image: "docker.io/library/python:3-alpine"
      working_container:
        volumes:
          - '{{ playbook_dir }}:/src:z'
      target_image:
        name: a-very-nice-image
        working_dir: /src
        labels:
          built-by: 'jms'
        environment:
          FILE_TO_PROCESS: README.md
  tasks:
  - name: Run a sample command
    command: 'ls -lha /src'
  - name: Stat a file
    stat:
      path: "{{ lookup('env','FILE_TO_PROCESS') }}"
