---
name: Test ansible-bender build

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install packages
        run: sudo apt-get install buildah

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
          cache: "pip"

      - name: Build image
        run: ansible-bender build ./services.yml
